[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "queuectl"
version = "0.1.0"
description = "A CLI background job queue in Python"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "click",
]

[project.scripts]
queuectl = "queuectl.cli:main"
